import type { Config } from "tailwindcss";

/** Tokens from DESIGN.md / stich code.html — single source of truth. */
const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#f3eaff",
        "surface-dim": "#dfd6ef",
        "secondary-fixed": "#e8ddff",
        "on-secondary-fixed-variant": "#4c3d77",
        "on-background": "#1e192b",
        outline: "#89726b",
        "outline-variant": "#dcc0b9",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#eee4fd",
        "secondary-fixed-dim": "#cebdff",
        "tertiary-fixed": "#c3ecd8",
        "on-tertiary-fixed": "#002116",
        "surface-tint": "#9e4225",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#564782",
        error: "#ba1a1a",
        "inverse-surface": "#332d40",
        "primary-fixed-dim": "#ffb59f",
        "on-primary-fixed": "#3a0a00",
        "inverse-primary": "#ffb59f",
        secondary: "#645591",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#214638",
        "surface-container-highest": "#e8def8",
        "tertiary-fixed-dim": "#a7cfbc",
        "on-secondary-fixed": "#200f49",
        "primary-container": "#ff8c69",
        "primary-fixed": "#ffdbd1",
        "surface-variant": "#e8def8",
        tertiary: "#416656",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#cbbafd",
        primary: "#9e4225",
        background: "#fdf7ff",
        "on-tertiary-fixed-variant": "#294e3f",
        "inverse-on-surface": "#f6eeff",
        "tertiary-container": "#8db4a2",
        "on-error": "#ffffff",
        "on-surface": "#1e192b",
        "surface-container-low": "#f8f1ff",
        surface: "#fdf7ff",
        "on-error-container": "#93000a",
        "surface-bright": "#fdf7ff",
        "on-surface-variant": "#56423d",
        "on-primary-fixed-variant": "#7e2b10",
        "on-primary-container": "#752409",
        cream: "#FFF8F0",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        card: "28px",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "24px",
        "margin-desktop": "64px",
        gutter: "20px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px",
        base: "8px",
      },
      fontFamily: {
        quicksand: ["var(--font-quicksand)", "Quicksand", "sans-serif"],
        nunito: ["var(--font-nunito)", "Nunito Sans", "sans-serif"],
        display: ["var(--font-quicksand)", "Quicksand", "sans-serif"],
        "headline-lg": ["var(--font-quicksand)", "Quicksand", "sans-serif"],
        "headline-md": ["var(--font-quicksand)", "Quicksand", "sans-serif"],
        "label-lg": ["var(--font-quicksand)", "Quicksand", "sans-serif"],
        "label-md": ["var(--font-quicksand)", "Quicksand", "sans-serif"],
        "body-lg": ["var(--font-nunito)", "Nunito Sans", "sans-serif"],
        "body-md": ["var(--font-nunito)", "Nunito Sans", "sans-serif"],
      },
      fontSize: {
        display: ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
      boxShadow: {
        soft: "0 20px 40px -15px rgba(100, 85, 145, 0.08)",
        "soft-hover": "0 30px 50px -20px rgba(100, 85, 145, 0.12)",
      },
      maxWidth: {
        content: "1200px",
      },
    },
  },
};

export default config;
